backend:
  name: git-gateway
  branch: master
  commit_messages:
    create: 'Create {{collection}} “{{slug}}”'
    update: 'Update {{collection}} “{{slug}}”'
    delete: 'Delete {{collection}} “{{slug}}”'
    uploadMedia: '[skip ci] Upload “{{path}}”'
    deleteMedia: '[skip ci] Delete “{{path}}”'

media_folder: static/img
public_folder: /img

collections:
  - name: "services"
    label: "Services"
    folder: "src/pages/services"
    create: true
    slug: "{{slug}}"
    extension: "mdx"
    format: "frontmatter"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "service-page"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Featured Image", name: "featuredimage", widget: image}
      - {label: "Service Intro", name: "serviceIntro", widget: "object", fields: [{label: "Text", name: "text", widget: "text"}, {label: "Action Label", name: "actionLabel", widget: "string"}, {label: "Action URL", name: "actionUrl", widget: "string"}]}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "pages"
    label: "Pages"
    folder: "src/pages/page"
    create: true
    slug: "{{slug}}"
    extension: "mdx"
    format: "frontmatter"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "default-page"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Featured Image", name: "featuredimage", widget: image}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "menu"
    label: "Menu"
    folder: "src/menu"
    editor:
      disable_preview: true
    create: true
    fields:
      - label: Type
        name: type
        widget: hidden
        default: menu
      - label: Title
        name: title
        widget: string
      - label: "Menu Items"
        name: menuItems
        widget: list
        types:
          - label: Link
            name: link
            widget: object
            fields:
              - label: Title
                name: title
                widget: string
              - label: Path
                name: path
                widget: string
          - label: Dropdown
            name: dropdown
            widget: object
            fields:
              - label: Title
                name: title
                widget: string
              - label: "Dropdown Item"
                name: dropdownItems
                widget: list
                fields:
                  - label: Icon
                    name: icon
                    widget: image
                  - label: Title
                    name: title
                    widget: string
                  - label: Description
                    name: description
                    widget: string
                  - label: Path
                    name: path
                    widget: string

  - name: "customPages"
    label: "Custom Pages"
    files:

      - file: "src/pages/index.md"
        label: "Landing Page"
        name: "index"
        fields:
          - label: "Template Key"
            name: "templateKey"
            widget: "hidden"
            default: "index-page"
          - label: Image
            name: image
            widget: image
          - label: Heading
            name: heading
            widget: string
          - label: Subheading
            name: subheading
            widget: string
          - label: Intro
            name: intro
            widget: object
            fields:
              - label: Heading
                name: heading
                widget: string
              - label: Subheading
                name: subheading
                widget: string
              - label: Description
                name: description
                widget: text
              - label: Blurbs
                name: blurbs
                widget: list
                fields:
                  - label: Image
                    name: image
                    widget: image
                  - label: Text
                    name: text
                    widget: text
          - label: About
            name: about
            widget: object
            fields:
              - label: Heading
                name: heading
                widget: string
              - label: Subheading
                name: subheading
                widget: string
              - label: Image
                name: image
                widget: image
              - label: Blurbs
                name: blurbs
                widget: object
                fields:
                  - label: Heading
                    name: heading
                    widget: string
                  - label: Text
                    name: text
                    widget: string
                  - label: Icon
                    name: icon
                    widget: image
          - label: "Testimonials Tag"
            name: testimonialsTag
            widget: string
          - label: "Gallery Preview"
            name: galleryPreview
            widget: object
            fields:
              - label: Heading
                name: heading
                widget: string
              - label: "Link Text"
                name: linkText
                widget: string
              - label: "Link URL"
                name: linkUrl
                widget: string
              - label: Items
                name: items
                widget: list
                fields:
                  - label: Image
                    name: image
                    widget: image
                  - label: Alt
                    name: alt
                    widget: string
          - label: Brands
            name: brands
            widget: list
            fields:
              - label: Image
                name: image
                widget: image
              - label: Alt
                name: alt
                widget: string

      - file: "src/pages/contact/index.mdx"
        label: "Contact Page"
        name: "contact"
        format: yaml-frontmatter
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "contact-page"}
          - {label: Title, name: title, widget: string}
          - {label: Heading, name: heading, widget: string}
          - {label: Subheading, name: subheading, widget: string}
          - {label: Image, name: image, widget: image}
          - {label: "Form Header", name: formHeader, widget: string}
          - {label: Email, name: email, widget: string}
          - {label: Phone, name: phone, widget: string}
          - {label: Testimonials Tag, name: testimonialsTag, widget: string}
          - label: Locations
            name: locations
            widget: list
            fields:
              - label: Title
                name: title
                widget: string
              - label: Address
                name: address
                widget: markdown
                minimal: true

      - file: "src/pages/gallery.md"
        label: "Gallery Page"
        name: "gallery"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "gallery-page"}
          - {label: Title, name: title, widget: string}
          - {label: "Featured Image", name: "featuredimage", widget: image}
          - {label: Heading, name: heading, widget: string}
          - {label: Subheading, name: subheading, widget: string}
          - {label: Description, name: description, widget: string}
          - {label: "Action Link", name: actionLink, widget: object, fields: [{label: Text, name: text, widget: string}, {label: Url, name: url, widget: string}]}
          - {label: Gallery, name: gallery, widget: list, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}

  - name: "testimonials"
    label: "Testimonials"
    files:
      - file: "src/testimonials/index.md"
        label: "All Testimonials"
        name: "testimonials"
        editor:
          disable_preview: true
        fields:
          - label: Type
            name: type
            widget: hidden
            default: "testimonials"
          - label: Testimonials
            name: testimonials
            widget: list
            fields:
              - label: Quote
                name: quote
                widget: string
              - label: Author
                name: author
                widget: string
              - label: Company
                name: company
                widget: string
              - label: Avatar
                name: avatar
                widget: image
              - label: Tags
                name: tags
                widget: list